server:
  port: 8081

spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/SENG400"
        username: root
        password: a7P4sdgr

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update